### PR TITLE
Add tests for HTTP server side.

### PR DESCRIPTION
**Pull request by pyfisch**
Currently failing tests are marked with #[should_panic]

See also #23

### CODE REVIEW

**Comment by tailhook** [comment]
Hm, I'm not sure what to do with `\n\n`. Current implementation is simple, and I have always thought that the only reason to support LF without CR is just to do telnet-test easier. But it complicates implementation.

IIRC, hyper just parses with `httparse` on each network packet. While it doesn't make any memory allocations I'm not sure it's the most performant way to handle headers. The overhead is definitely non-visible in micro-benchmarks where headers always fit in single packet, but in real-life headers often do not fit, AFAIK.

Thoughts?

**Comment by pyfisch** [comment]
Hm, some thoughts: I think rotor-http should strive to be correct even if it includes some sort of performance penality. I have done some research on request header sizes. On a page without cookies the Firefox headers sent are 0.4KB, for Google they are 1.3KB and for Github 0.9KB. The best statistics I could find were from Google too:
> Uncompressed request and response headers. Request headers today vary in size from ~200 bytes to over 2KB.  As applications use more cookies and user agents expand features, typical header sizes of 700-800 bytes is common. [SPDY whitepaper](http://dev.chromium.org/spdy/spdy-whitepaper)

So in most cases they will be sent in multiple packages. However the focus of `httparse` is speed and I doubt that one can be faster in determining header size and parsing them (with current Rust). seanmonstar has researched fast header parsing quite much. AFAIK `rotor-stream` must search for `\r\n\r\n` in the input stream too, so you have two passes instead of one with `httparse`. (Probably `rotor-stream` has some kinds of optimization I do not know of like only checking newly received bytes) One upside of using `httparse` is that `rotor-http` discovers protocol mismatch and malformed requests early. I think a micro-benchmark can be written that simulates many individual packages by appending always some bytes to the input buffer and then compare the performance of searching for `\r\n\r\n` and `httparse`. Another advantage is that the header length is always correctly determined, this prevents bugs like the one shown in `test_broken_http()`.

**Comment by pyfisch** [comment]
I have written a small request parse bench: 24a3c354a1dd4958ffe16afa104ed11781709a85 The simulated server parses a request of six "packets". It needs 22,044 ns/iter (+/- 758) to execute, this is five times slower than with just one packet.

**Comment by tailhook** [comment]
Well, the difference is quite big. Old numbers:
```
test server::parser::test::bench_parse1 ... bench:       6,639 ns/iter (+/- 265)
test server::parser::test::bench_parse6 ... bench:      23,489 ns/iter (+/- 4,458)
```
New numbers (using httparse for delimitation):
```
test server::parser::test::bench_parse1 ... bench:       6,557 ns/iter (+/- 183)
test server::parser::test::bench_parse6 ... bench:     205,320 ns/iter (+/- 17,277)
```
Its based on your test, first test has one slice (your test with collapsed calls). Second test has 6 packets (https://github.com/tailhook/rotor-http/tree/check-headers-httparse-dirty-hack).
The code is just a dirty hack for now. So maybe I'm doing something wrong.

But if the difference is really like this, then it's not negligible in my opinion. During 200 microseconds python code can do two round-trips to a memcached or redis (just to have a point for comparison)

**Comment by tailhook** [comment]
Notes to myself:

* removing client address doesn't help too much
* setting MAX_HEADERS_NUM to 16, changed time to 149,009 ns/iter (+/- 3,616), which means just resetting the memory already takes too much time
* find_substr is about 4x faster than parsin headers on microbenchmark

Because of these I'm not sure where 120,000 ns are spent? Between the layers of Stream and Parser? But it's late night, so I'm sure I'm missing something...

**Comment by pyfisch** [comment]
I've found the problem. `bytes_read` is called after every single byte (a total of 391 calls). This is because of `rotor-stream`. To make the issue visible add `println!("read headers {:?}", x);` after line 392 in `server/parser.rs`.

**Comment by tailhook** [comment]
Thanks! I just hadn't had a chance to check that yet. 054b70e works fine:
```
test server::parser::test::bench_parse1 ... bench:       6,517 ns/iter (+/- 136)
test server::parser::test::bench_parse6 ... bench:      25,718 ns/iter (+/- 752)
```

**Comment by pyfisch** [comment]
The numbers look good. httparse is not (much?) slower than the code before.

**Comment by pyfisch** [comment]
I am preparing a pull request to accept all line endings.

**Comment by tailhook** [comment]
@pyfisch okay. But perhaps, you shouldn't touch *client* implementation. I'm currently changing the API.

**Comment by tailhook** [comment]
Is this superseded by #28?

**Comment by pyfisch** [comment]
Yes, kind of.

**Pull request closed without merging**
