### PR TITLE
WIP: Remove duplicate code and move common code to shared/

### PR DESCRIPTION
**Pull request by pyfisch**

### CODE REVIEW

**Comment by tailhook** [comment]
Do you have any good reasons to unify BodyKind type? This is a type which users will match directly, so requiring them to use `Eof => unreachable!()` in every server-side implementation is ugly. Not sure about Upgrade yet.

I don't think there is a cost to keep enumerations separate.

**Comment by pyfisch** [comment]
I did unify them to be able to pass them to `BodyProgress::start()`. If they are kept separate for client and server we will need two methods.

**Comment by tailhook** [comment]
Well, after re-reading the patch, I'm not sure that unifying BodyProgress makes much sense. Now you have `xxEof => unreachable!()`. 

While initially, I thought that much body parsing can be unified in client and server, while writing the client I don't think so. Many differences are attributed to error handling.

So is it a part of some higher-level strategy, or you just wanted to remove seemingly duplicate code?

**Comment by pyfisch** [comment]
I think the body parsing code can be unified. Why don't you thing so?

**Comment by tailhook** [comment]
Because the complex part is likely this: https://github.com/tailhook/rotor-http/blob/master/src/server/parser.rs#L393-L517

There is only one piece of "parsing", it's chunk size (which should use a function from httparse anyway). Most of other code are about correct passing the chunks to the child state machine and error reporting. Child state machine is different, and error handling is a bit different too.

So you may probably try to do it. Maybe your mileage will be better.

**Comment by pyfisch** [comment]
chunk size parsing is implemented in httparse: http://seanmonstar.github.io/httparse/httparse/fn.parse_chunk_size.html

**Comment by tailhook** [comment]
Yes. That's what I have said too.  (I just wasn't aware of that when writing the code. But that wasn't a hard part anyway)

**Comment by tailhook** [comment]
@pyfisch, do you work on this at the moment? I'm largely refactoring rotor to fix the timeouts (tailhook/rotor#12), and I'm going to catch up with all this quickly. And there might be small changes all over the code (because return values will likely change), so perhaps it would be hard to merge.

**Comment by pyfisch** [comment]
No I am not currently working on it.

**Pull request closed without merging**
