### PR TITLE
remove all uses of hyper version enum

### PR DESCRIPTION
**Pull request by pyfisch**

### CODE REVIEW

**Comment by pyfisch** [comment]
I am not sure if tHTTP/0.9 should be part of the version enum.

**Comment by tailhook** [comment]
Yes, I think we should not introduce an Http09 at all.

**Comment by pyfisch** [comment]
Rebased and removed Http09.

**Comment by tailhook** [comment]
Thanks!

BTW, feel free to add yourself to authors list and/or copyright.

**Pull request merged**
