### PR TITLE
Add Todo-Backend implementation in rotor-http.

### PR DESCRIPTION
**Pull request by pyfisch**
(This should show users how to build simple web services with a bit more functionality than hello-world. Feel free to ignore this PR if you do not want such examples inside rotor-http.

### CODE REVIEW

**Comment by tailhook** [comment]
It's cool example, but I want examples to work with stable rust. Can you use `rustc_serialize` ?

**Comment by pyfisch** [comment]
I have not yet used `rustc_serialize` but I will try to get `serde` working with stable rust.

**Comment by tailhook** [comment]
Or it may be possible to build example only with `--feature nightly` (not sure if there is an easy way to do that, though)

**Comment by pyfisch** [comment]
The todobackend example now only builds with --feature nightly.

**Comment by pyfisch** [comment]
Now it finally works.

**Comment by tailhook** [comment]
Merged. Thanks!

**Comment by tailhook** [comment]
Do you have a frontend for the example? I would be nice to have fully working application published somewhere? Probably separate repo, linked in the docs and [ecosystem](http://rotor.readthedocs.org/en/latest/ecosystem.html)

**Comment by pyfisch** [comment]
I don't have a webserver where I could host this todo app at the moment. What do we want to show with this app? Just that rotor-http works? Using rotor-http directly is very verbose so this is no code to impress anyone. Frontend is at http://todobackend.com/client/index.html?http://localhost:3000 if you execute it.

**Comment by tailhook** [comment]
Well, I'll probably find some place to host it, but.. 

The demo repository is good for people to start coding it. Like if I could clone and run todo out of the box, I could experiment with it. Making it from scratch would probably require too much learning from the start.

Maintaining separate repo at this stage may require too much effort, though.

**Pull request merged**
