### PR TITLE
use String instead of RequestUri for HTTP path

### PR DESCRIPTION
**Pull request by pyfisch**
Addresses #8. Do not merge yet.

You said the path could be a slice of a buffer, but using `&str` with the current code does not work since the `Transport` in `parse_headers` is borrowed too long mutably by Head. I think it is possible to use slices but `parse_headers` needs to be rewritten. Maybe it would be easier if the headers weren't passed to `request_start` again?

### CODE REVIEW

**Comment by tailhook** [comment]
Hm, the idea was that Head is passed *by reference* to the headers_received, because rotor still needs some info from headers. Then it passes ownership to the application in request_start.

Perhaps it's possible to extract everything needed before executing headers_received (if it doesn't require to clone/allocate memory). Then we can get rid of request_start entirely.

**Comment by pyfisch** [comment]
* `fn headers_received(head: &Head, scope: &mut Scope<Self::Context>)
        -> Result<(Self, RecvMode, Deadline), StatusCode>;`
* `fn request_start(self, head: Head, response: &mut Response,
        scope: &mut Scope<Self::Context>)
        -> Option<Self>;`

The methods differ in their return type and that `request_start` expects a response object. If `request_start` is removed there is no way to construct the response immediatly after the headers were received or should the `headers_received` method be extended to accept a response object?

**Comment by tailhook** [comment]
> or should the headers_received method be extended to accept a response object?

Yes, exactly. (or at least I don't see any difficulties with that at the moment)

**Comment by pyfisch** [comment]
There may be a slight increase in memory allocation because the `Response` is also created for failing requests.

**Comment by tailhook** [comment]
> There may be a slight increase in memory allocation because the Response is also created for failing requests.

No, Response does not have heap allocated parts.

**Pull request closed without merging**
